# Generated by Django 3.1.2 on 2021-01-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
