# Generated by Django 3.1.2 on 2021-01-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="note",
            new_name="notebook",
        ),
    ]
