# Generated by Django 3.1.2 on 2021-01-24 11:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_auto_20210123_1730"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="ok",
                editable=False,
                populate_from="name",
                unique=True,
                verbose_name="Nom de l'espace de travail'",
            ),
            preserve_default=False,
        ),
    ]
