# Generated by Django 3.0.11 on 2021-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20210210_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='category',
            field=models.CharField(choices=[('tous', 'Tous'), ('maintenance', 'Maintenance'), ('etage', 'Étage')], default='tous', help_text='Use to display certains notes for a specific group of users, by default messages are shown to everyone', max_length=20, verbose_name='Category'),
        ),
    ]
