# Generated by Django 3.1.2 on 2021-02-11 14:53

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_auto_20210210_1820"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 2, 11, 14, 53, 55, 942811, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
