# Generated by Django 3.1.2 on 2021-02-11 16:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0004_notebook_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
