# Generated by Django 3.1.2 on 2021-02-12 08:39

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0005_auto_20210212_0939"),
        ("workspace", "0005_auto_20210211_1744"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
            },
        ),
        migrations.AlterModelOptions(
            name="notebook",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="workspace",
            options={
                "verbose_name": "Espace de travail",
                "verbose_name_plural": "Espaces de travail",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="L'auteur qui sera associé au commentaire",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="notebook",
            field=models.ForeignKey(
                help_text="Le message associé au commentaire que vous ajouter ou ",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="workspace.notebook",
                verbose_name="Message",
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="category",
            field=models.CharField(
                choices=[
                    ("tous", "Tous"),
                    ("maintenance", "Maintenance"),
                    ("etage", "Étage"),
                ],
                default="tous",
                help_text="Catégories utilisées pour filtrer et associer des consignes et messages",
                max_length=20,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenu du message"
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="is_done",
            field=models.BooleanField(
                default=False,
                help_text="Si la case est cochée, le message est considéré comme fait et affiche un label sur le contenu",
                verbose_name="Fait",
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Si la case est cochée, le message est considéré comme épinglé et affiche un label sur le contenu",
                verbose_name="Épinglé",
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="tag_user",
            field=models.ManyToManyField(
                blank=True,
                help_text="Les utilisateurs selectionnés recevront une notification",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateurs taggués",
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace is linked to a property, the workspace is where users exchange informations",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="workspace.workspace",
                verbose_name="Espace de travail",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="property",
            field=models.OneToOneField(
                help_text="Property related to the current workspace",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace",
                to="properties.property",
                verbose_name="Établissement",
            ),
        ),
    ]
