# Generated by Django 3.0.11 on 2021-02-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_auto_20210127_2119"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="If set to true the note is mark as pinned and show on the dashboard",
            ),
        ),
    ]
