# Generated by Django 3.1.2 on 2021-02-08 13:28

import autoslug.fields
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_auto_20210203_1752"),
        ("workspace", "0010_auto_20210203_1752"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(
                help_text="Workspace name, by default is the name of the property",
                max_length=50,
                verbose_name="Nom de l'espace de travail",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="property",
            field=models.ForeignKey(
                help_text="Property related to the current workspace",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace",
                to="property.property",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                help_text="Slug used for custom link",
                populate_from="name",
                unique=True,
                verbose_name="Nom de l'espace de travail'",
            ),
        ),
    ]
