# Generated by Django 3.0.11 on 2021-02-10 15:31

import autoslug.fields
from django.conf import settings
from django.db import migrations
from django.db import models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name will be used to identify the property",
                        max_length=50,
                        verbose_name="Nom de l'établissement",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="Nom de l'établissement",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="If true property has premium features"
                    ),
                ),
                (
                    "collaborator",
                    models.ManyToManyField(
                        help_text="Users selected will have full access to the property and the workspace related",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Collaborateurs",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
    ]
