# Generated by Django 3.1.2 on 2021-04-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_sponsors',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('document', 'Document'), ('checklist', 'Checklist'), ('planning', 'Planning')], default='document', help_text='Catégories utilisées pour filtrer les fichiers', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_premium',
            field=models.BooleanField(default=False, help_text="Si coché, votre établissement dispose d'un compte premium", verbose_name='Premium'),
        ),
    ]
