# Generated by Django 3.1.2 on 2021-02-11 21:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="checklist",
            field=models.FileField(
                blank=True,
                help_text="If true property has premium features",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="planning",
            field=models.FileField(
                blank=True,
                help_text="If true property has premium features",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.TextField(
                help_text="The name will be used to identify the property",
                verbose_name="Ordre du jour",
            ),
        ),
    ]
