# Generated by Django 3.1.2 on 2021-02-11 21:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_auto_20210211_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="notice",
            field=models.TextField(
                blank=True,
                help_text="The name will be used to identify the property",
                null=True,
                verbose_name="Ordre du jour",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(
                help_text="The name will be used to identify the property",
                max_length=50,
                verbose_name="Nom de l'établissement",
            ),
        ),
    ]
