# Generated by Django 3.1.2 on 2021-02-12 08:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_auto_20210211_2215"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_sponsors",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, vous disposez de fonctionnalités exlusives et de contenu illimité",
                verbose_name="Offre sponsors",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_premium",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, vous disposez de fonctionnalités exlusives et de contenu illimité",
                verbose_name="Offre premium",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(
                help_text="Le nom de votre établissement",
                max_length=50,
                verbose_name="Nom de l'établissement",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="notice",
            field=models.TextField(
                blank=True,
                help_text="L'ordre du jour apparaitra sur le tableau de bord de votre équipe",
                null=True,
                verbose_name="Ordre du jour",
            ),
        ),
    ]
