# Generated by Django 3.1.2 on 2021-02-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_auto_20210212_0921"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={
                "verbose_name": "Établissement",
                "verbose_name_plural": "Établissements",
            },
        ),
    ]
