# Generated by Django 3.1.2 on 2021-02-12 08:58

from django.db import migrations
from django.db import models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_auto_20210212_0939"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="checklist",
        ),
        migrations.RemoveField(
            model_name="property",
            name="planning",
        ),
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "planning",
                    models.FileField(
                        blank=True,
                        help_text="Un planning disponible au téléchargement par votre équipe",
                        null=True,
                        upload_to="",
                        verbose_name="Planning",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Description de votre planning, laissez vide si besoin",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "properties",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plannings",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Un fichier disponible au téléchargement par votre équipe",
                        null=True,
                        upload_to="",
                        verbose_name="Document",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Description de votre fichier, laissez vide si besoin",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "properties",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "checklist",
                    models.FileField(
                        blank=True,
                        help_text="Une checklist disponible au téléchargement par votre équipe",
                        null=True,
                        upload_to="",
                        verbose_name="Checklist",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Description de votre checklist, laissez vide si besoin",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "properties",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
