# Generated by Django 3.1.2 on 2021-02-12 13:45

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0006_auto_20210212_0958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="collaborator",
            field=models.ManyToManyField(
                help_text="Les utilisateurs ajoutés auront accès à l'application web",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Collaborateurs",
            ),
        ),
    ]
