# Generated by Django 3.1.2 on 2021-02-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_auto_20210212_1445"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="checklist",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="document",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="planning",
            old_name="planning",
            new_name="file",
        ),
    ]
