exclude: 'docs|node_modules|migrations|.git|.tox|static|staticfiles'
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black
        entry: black frontdesk

  #- repo: https://gitlab.com/pycqa/flake8
   # rev: 3.8.4
   # hooks:
    #  - id: flake8
    #    args: ['--config=setup.cfg']
