name: CI 
language: python
python: 
  - "3.8" # Current default Python version for the project


env: DJANGO_SETTINGS_MODULE="config.settings.test"

before_script:
  - psql -c "CREATE USER gaetan WITH PASSWORD 'password';" -U postgres
  - psql -c 'create database test_db;' -U postgres
  
# Update PIP
before_install:
  - python -m pip install --upgrade pip
# Install dependecies from local requirements
install:
  - pip install -r requirements.txt

services:
  - postgresql

script:
  - pytest
  - black .
  - isort .