# Generated by Django 3.1.2 on 2021-02-14 17:37

from django.db import migrations
from django.db import models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="If set to true the notification is highlighted in the notification dropdown",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("notification", "Notification"),
                            ("tag", "Tag"),
                            ("message", "message"),
                            ("pinned", "Pinned"),
                            ("system", "System"),
                        ],
                        default="message",
                        help_text="Use for categorize notifications",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
