# Generated by Django 3.1.2 on 2021-04-16 08:42

from django.db import migrations
from django.db import models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenu de la tâche"
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False,
                        help_text="Si la case est cochée, la tâche n'apparait plus sur la checklist",
                        verbose_name="Fait",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Matin", "Matin"),
                            ("Après-midi", "Après-midi"),
                            ("Soir", "Soir"),
                        ],
                        default="Matin",
                        help_text="Catégories utilisées pour filtrer et associer les tâches",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
            },
        ),
    ]
