# Generated by Django 3.1.2 on 2021-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Matin', 'Matin'), ('Après-midi', 'Après-midi'), ('Soir', 'Soir'), ('Nuit', 'Nuit')], default='Matin', help_text='Catégories utilisées pour filtrer et associer les tâches', max_length=20, verbose_name='Catégorie'),
        ),
    ]
