# Generated by Django 3.1.2 on 2021-04-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210414_1238'),
        ('checklist', '0002_auto_20210317_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='property',
            field=models.ForeignKey(help_text='Établissement', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='properties.property', verbose_name='Établissement'),
        ),
    ]
