# Generated by Django 3.1.2 on 2021-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20210414_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Matin', 'Matin'), ('Après-midi', 'Après-midi'), ('Soir', 'Soir')], default='Matin', help_text='Catégories utilisées pour filtrer et associer les tâches', max_length=20, verbose_name='Catégorie'),
        ),
    ]
