# Generated by Django 3.1.2 on 2021-02-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210215_1627'),
        ('users', '0002_auto_20210215_1632'),
    ]

    operations = [
    ]
