# Generated by Django 3.1.2 on 2021-02-12 13:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210212_1105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Précise si l’utilisateur est administrateur, l'administrateur est le seul rôle permettant de supprimer et modifier un établissement, ainsi que supprimer un utilisateur",
                verbose_name="Administrateur",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Rôle dans l'entreprise, (ex: directeur, réceptionniste ..)",
                max_length=200,
                null=True,
            ),
        ),
    ]
