# Generated by Django 3.0.11 on 2021-02-22 12:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_merge_20210215_1814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="first name"),
        ),
    ]
