# Generated by Django 3.0.11 on 2021-02-01 21:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, max_length=254, null=True, upload_to="media"
            ),
        ),
    ]
