# Generated by Django 3.1.2 on 2021-02-05 15:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="request",
            field=models.TextField(
                blank=True,
                help_text="Can be used to specify request to the manager, holiday, specifi work days ...",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Short description use in member card", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="note",
            field=models.TextField(
                blank=True, help_text="Privates notes shown on the dashboard", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Job title to identify which departement the user belongs to",
                max_length=200,
                null=True,
            ),
        ),
    ]
