# Generated by Django 3.0.11 on 2021-01-07 22:27

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='établissemment')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name="Nom de l'établissement")),
                ('token', models.CharField(blank=True, help_text='Token to secure the workspace, each token are unique and should use an universally unique identifier ', max_length=500)),
                ('collaborator', models.ManyToManyField(related_name='collaborator', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
