# Generated by Django 3.0.11 on 2021-01-17 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='collaborator',
            field=models.ManyToManyField(related_name='property', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs'),
        ),
    ]
