# Generated by Django 3.0.11 on 2021-01-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="token",
        ),
    ]
