# Generated by Django 3.1.2 on 2021-01-08 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0002_remove_property_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="collaborator",
            field=models.ManyToManyField(
                related_name="collaborators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Collaborateurs",
            ),
        ),
    ]
