# Generated by Django 3.1.2 on 2021-01-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_auto_20210123_1156"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertypermission",
            options={"verbose_name_plural": "Properties permissions"},
        ),
    ]
