# Generated by Django 3.0.11 on 2021-02-03 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0003_auto_20210123_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="collaborator",
            field=models.ManyToManyField(
                help_text="Users selected will have full access to the property and the workspace related",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Collaborateurs",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(
                help_text="The name will be used to identify the property",
                max_length=50,
                verbose_name="Nom de l'établissement",
            ),
        ),
    ]
