name: Front Desk Build

on: [push]

jobs:
  build:
    env:
      ENV_MANAGE: 'PRODUCTION'
      DJANGO_SETTINGS_MODULE: 'config.settings.test'
      DATABASE_NAME: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      SECRET_KEY: 'you-will-never-guess'

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python 3.7
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run migrations
      run: python manage.py migrate
   
    - name: Linting and formating
      run: | 
        black .
        isort .
        
    - name: Run tests
      run: pytest